### ISSUE TITLE
IndexError when the string provided does not contain number

### ISSUE THREAD

**Issue by ArnaudLevaufre** [akshaynagpal/w2n#1]
```python
>>> w2n.word_to_num("coucou")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arnaud/projects/cinema/venv/lib/python3.5/site-packages/word2number/w2n.py", line 98, in word_to_num
    hundreds = number_formation(clean_numbers)
  File "/home/arnaud/projects/cinema/venv/lib/python3.5/site-packages/word2number/w2n.py", line 120, in number_formation
    return numbers[0]
IndexError: list index out of range
```

**Comment by akshaynagpal** [comment]
Thank you ArnaudLevaufre for pointing this out, will surely improve this in the next release. 
Also,I saw your Python version is 3.5. Just for information, this package is for Python 2.x currently.

**Comment by akshaynagpal** [comment]
Solved by commit no. [bebc681149c325b2c119b5297382ed20dc246487](https://github.com/akshaynagpal/w2n/commit/bebc681149c325b2c119b5297382ed20dc246487)

Will be available from next release!

**Comment by akshaynagpal** [comment]
Solved by commit no. [bebc681149c325b2c119b5297382ed20dc246487](https://github.com/akshaynagpal/w2n/commit/bebc681149c325b2c119b5297382ed20dc246487)

Will be available from next release!
