### ISSUE TITLE
Using "Raise" for error reporting instead of print

### ISSUE THREAD

**Issue by Apaar** [akshaynagpal/w2n#12]
Why are we printing error messages instead or raising them? 
Because of the print we are unable to to ignore or handle the error(try-catch).There is also no way to test if the library will accept a given string. So we cannot completely avoid a error message being printed in console if input is user generated apart from testing for a lot of rules based on the semantics of your library's functions.

**Comment by akshaynagpal** [comment]
@Apaar 
Thanks for pointing this out. I will look into this ASAP. 
Meanwhile, you're also welcome to fix the error and submit a Pull Request. If it passes all the tests, it will be merged most probably.

**Comment by danielhers** [comment]
I agree, it would be much more pythonic and useful to raise an exception that can be caught, instead of printing to standard output and returning `None`.

**Comment by akshaynagpal** [comment]
Thanks @danielhers . Done ! :)
