### ISSUE TITLE
does not work well with unicode string

### ISSUE THREAD

**Issue by irfan-zoefit** [akshaynagpal/w2n#18]
```python
qty=u'two'
w2n.word_to_num(qty)
```
throws error

```shell
{ValueError}Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')
```
Could you make it to work with unicode?

**Comment by akshaynagpal** [comment]
@irfan-zoefit It won't and **should not** work with unicode. It clearly says it expects string as an input. That's what verbose errors are for. Also, there are 2 approaches to taking inputs for any library/method. 
1. Take any type of input and convert it to the expected datatype (string in this case)
2. Accept just a single type of input and have verbose errors in case the input is not of the expected type.

Right now, w2n goes with 2. If it goes with 1 in future, sure I will add auto-convert to string. But right now that's kind of ambiguous and less specific. 

Thanks anyway.
