### ISSUE TITLE
Replacing word numbers with digits in a string

### ISSUE THREAD

**Issue by psychemedia** [akshaynagpal/w2n#39]
`word2number` seems to be able to pull numbers from words out of a more general string:

```
w2n.word_to_num("I count it at two million three thousand nine hundred and eighty four or thereabouts")

#returns: 2003984
```

but is there also a way of plugging that back in to the original string?

For example, if I wanted something like:

```
w2n.word_to_num("I count it at two million three thousand nine hundred and eighty four or thereabouts", replace=True)

#returns: "I count it at 2003984 or thereabouts"
```

**Comment by akshaynagpal** [comment]
Not as of now. You will have to process that with additional code at your end.
