### ISSUE TITLE
module 'word2number' has no attribute 'word_to_num'

### ISSUE THREAD

**Issue by kareemostafa** [akshaynagpal/w2n#49]
After installing word2number using pip I get the following message every time I try and use the "word_to_num" function.

module 'word2number' has no attribute 'word_to_num'

Any idea what is causing this?

Thanks in advance,

**Comment by akshaynagpal** [comment]
Please post sample source code that is not working. Also, refer to examples in readme in case those help you fix the issue.

If it still doesn't work, reopen this with source code example that doesn't work.
