### ISSUE TITLE
Whats the difference to the repo w2ni18n ?

### ISSUE THREAD

**Issue by yzhang123** [akshaynagpal/w2n#53]
Whats the difference to the repo w2ni18n ?

**Comment by bastie** [comment]
w2ni18n contains the language specific words in dynamic loaded resource files. You do not modify source code to add or change languages.
see https://github.com/bastie/w2ni18n/blob/master/README.md#i18n 

internal use w2ni18n RFC lang codes and for example on linux system take the LANG environment variable and some other fallbacks 

if you need only English it is same like w2n
