### ISSUE TITLE
w2n needs better error handling, idempotency

### ISSUE THREAD

**Issue by relwell** [akshaynagpal/w2n#7]
Please refer to the following line:

https://github.com/akshaynagpal/w2n/blob/master/word2number/w2n.py#L74

There should be a keyword argument to determine whether or not to raise an error or return the same value that was passed to the function.

This function should also be able to accommodate passing a numeric value and returning it without transforming it.

Currently, it's in somewhat the worst of all possible states, since we would actually need to perform text matching to determine whether an error was encountered. If I wanted to perform text matching, I would implement this library myself.

**Comment by akshaynagpal** [comment]
@relwell Thanks for pointing it out, I will keep this in mind while drafting the next release. Also, you can contribute too, by making the changes you've pointed out, and submitting a PR. Cheers!
