### ISSUE TITLE
New library with similar functionality- itnpy

### ISSUE THREAD

**Issue by brandhsu** [akshaynagpal/w2n#70]
Hi all, if you are seeing this, I am doing some personal marketing 😊.

This library is no longer activley maintained and contains several bugs that introduces unrecoverable errors. 

I have created [itnpy](https://github.com/Brandhsu/itnpy) that contains similar functionality and handles long number sequences well. It is also very short and easy to configure and modify for project specific needs.

**Comment by brandhsu** [comment]
For example, it handles these cases without any (unrecoverable) mistakes:

- #69 
- #66  
- #61 
- #58
- #45
- #44 
- etc.

**Comment by pandoman** [comment]
The link you provided for itnpy gives a 404 error

**Comment by princelySid** [comment]
I believe it's this one here: https://pypi.org/project/itnpy2/
